"""stratus/config.py"""

from enum import Enum
from pydantic import BaseModel
from typing import Any, Dict, List, Optional


class FieldType(str, Enum):
    """
    Tipos de campos en mensajes Stratus.
    """
    NUMERIC = "Numerico"
    ALPHANUMERIC = "Alfanumerico"

class FieldDefinition(BaseModel):
    """
    Definición de un campo en el mensaje Stratus.
    """
    name: str
    length: int
    position: int
    field_type: FieldType
    description: Optional[str] = None

class MessageType(str, Enum):
    """
    Tipos de mensajes Stratus.
    """
    ACF = "ACF"
    AFD = "AFD"

class StratusConfig:
    """
    Configuración para el procesador de mensajes Stratus.
    """
    # Longitud de de las tramas
    MESSAGE_LENGHTS = {
        MessageType.ACF: 940,
        MessageType.AFD: 1003
    }
    
    # Diccionario de campos de la trama ACF
    ACF_FIELDS: List[FieldDefinition] = [
        FieldDefinition(
        name="ByteI",
        length=5,
        position=1,
        field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="Constante",
            length=1,
            position=6,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="DiaSistema",
            length=2,
            position=7,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="MesSistema",
            length=2,
            position=9,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="AnioSistema",
            length=4,
            position=11,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="HoraSistema",
            length=2,
            position=15,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="MinutoSistema",
            length=2,
            position=17,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="ConstanteKey",
            length=5,
            position=19,
            field_type=FieldType.ALPHANUMERIC,
            description="Campo para identificar la trama ACF con los siguientes códigos '00745' OR '0074'"
        ),
        FieldDefinition(
            name="ConstanteBanco",
            length=10,
            position=24,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="TipoMensaje",
            length=4,
            position=34,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="TipoTarjetaTj",
            length=2,
            position=38,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="RestoTarjeta",
            length=17,
            position=40,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodigoTransaccionB24",
            length=2,
            position=57,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="TipoCuenta",
            length=4,
            position=59,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="IndicadorReverso",
            length=1,
            position=63,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="ValorTransaccion",
            length=14,
            position=64,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="ImporteTransaccion",
            length=14,
            position=78,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="FechaTrans",
            length=8,
            position=92,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="HoraTrans",
            length=6,
            position=100,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="TasaConversion",
            length=11,
            position=106,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="TalonTransaccion",
            length=6,
            position=117,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="HoraTransaccion",
            length=6,
            position=123,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="FechaTransaccion",
            length=8,
            position=129,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="FechaVencimientoTar",
            length=4,
            position=137,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="ModosProcesamiento",
            length=1,
            position=141,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="FechaAplicacion",
            length=8,
            position=142,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="CodigoAdqComercio",
            length=4,
            position=157,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="CodigoPaisInstAdq",
            length=3,
            position=154,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="CodigoPaisTarjeta",
            length=3,
            position=157,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="CodigoPaisInstEmisor",
            length=3,
            position=160,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="ModoEntrada",
            length=2,
            position=163,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CondicionPOS",
            length=2,
            position=165,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="NumeroPrincipalTarje",
            length=19,
            position=167,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodigoCondicionPOS",
            length=2,
            position=186,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="SectorActComercio",
            length=4,
            position=188,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="CodigoIdentificaAdq",
            length=11,
            position=192,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="CodigoIdentificaEmisor",
            length=11,
            position=203,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="NumeroAutorizacion",
            length=8,
            position=214,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodigoRespuesta",
            length=4,
            position=222,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="CodigoServicio",
            length=3,
            position=226,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="CodigoTerminal",
            length=8,
            position=229,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodigoComercio",
            length=15,
            position=237,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="NombreComercio",
            length=25,
            position=252,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="LocalidadComercio",
            length=13,
            position=277,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="PaisOrigenTransac",
            length=3,
            position=290,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="TipoTarjeta",
            length=2,
            position=293,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="NombreClienteTrack1",
            length=25,
            position=295,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="NombreClienteBuc",
            length=25,
            position=320,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodigoMonedaTrx",
            length=3,
            position=345,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="CodigoMonedaTitular",
            length=3,
            position=348,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="SaldoDisponible",
            length=14,
            position=351,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="PosicionGPS",
            length=14,
            position=365,
            field_type=FieldType.ALPHANUMERIC,
            description="Campo por cod_subproducto (entregados de la tabla 'sbl_productos_y_servicios"
        ),
        FieldDefinition(
            name="CupoTarjeta",
            length=12,
            position=379,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="CuentaOrigen",
            length=23,
            position=391,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CuentaDestino",
            length=23,
            position=414,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="BinTarjeta",
            length=6,
            position=437,
            field_type=FieldType.ALPHANUMERIC,
            description="No. tarjeta (identificados en la tabla 'sbl_fact_saldos')"
        ),
        FieldDefinition(
            name="BinLiquidadorBanco",
            length=6,
            position=443,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="EstadoTarjeta",
            length=10,
            position=449,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="IndTarjetaEmpleado",
            length=1,
            position=459,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="IndTarjetaAmparada",
            length=1,
            position=460,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="ValorMaxCompras",
            length=12,
            position=461,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="NumeroPuntos",
            length=12,
            position=473,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="OficinaRadicaTarjeta",
            length=6,
            position=485,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodigoIdentificaCliente",
            length=16,
            position=491,
            field_type=FieldType.NUMERIC,
            description="Nro de identificación de persona que hace el pago"
        ),
        FieldDefinition(
            name="PrimerNombreCliente",
            length=12,
            position=507,
            field_type=FieldType.ALPHANUMERIC,
            description="Primer Nombre persona que hace el pago"
        ),
        FieldDefinition(
            name="SegundoNombreCliente",
            length=12,
            position=519,
            field_type=FieldType.ALPHANUMERIC,
            description="Segundo Nombre persona que hace el pago"
        ),
        FieldDefinition(
            name="PrimerApellidoCliente",
            length=12,
            position=531,
            field_type=FieldType.ALPHANUMERIC,
            description="Primer Apellido persona que hace el pago"
        ),
        FieldDefinition(
            name="SegundoApellidoCliente",
            length=12,
            position=543,
            field_type=FieldType.ALPHANUMERIC,
            description="Segundo Apellido persona que hace el pago"
        ),
        FieldDefinition(
            name="NumeroIdentificaCliente",
            length=16,
            position=555,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="FechaNacimiento",
            length=8,
            position=571,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="EstadoCivil",
            length=12,
            position=579,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="DireccionCorresponden",
            length=35,
            position=591,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CorreoElectronico",
            length=35,
            position=626,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="TelefonoResidencia",
            length=12,
            position=661,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="TelefonoOficina",
            length=12,
            position=673,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="TelefonoCorresponden",
            length=12,
            position=685,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="TelefonoCelular",
            length=12,
            position=697,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="Usuario",
            length=12,
            position=709,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="OficinaRecaudo",
            length=4,
            position=721,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="NumeroCuenta",
            length=19,
            position=725,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="TipoIdentificacion",
            length=3,
            position=744,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodigoCanal",
            length=6,
            position=747,
            field_type=FieldType.NUMERIC,
            description="Campo para identificar las transacciones en oficina con el código '000000'"
        ),
        FieldDefinition(
            name="MedioTransaccional",
            length=4,
            position=753,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="MotivoConcepto",
            length=4,
            position=757,
            field_type=FieldType.NUMERIC,
            description="Campo para identificar los conceptos de transacción (cod_doc_funcional)"
        ),
        FieldDefinition(
            name="CodigoSupervisor",
            length=12,
            position=761,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="ValorCheque",
            length=14,
            position=773,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="LimiteDiarioCompras",
            length=6,
            position=787,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="ValorDiarioRetiros",
            length=6,
            position=793,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="CantDiariaRetiros",
            length=6,
            position=799,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="PaisTarjeta",
            length=22,
            position=813,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="BinVencimiento",
            length=10,
            position=835,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="OficinaTarjeta",
            length=22,
            position=845,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodigoComerciosPais",
            length=18,
            position=867,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="IndicadorFraude",
            length=1,
            position=885,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="ConstanteUno",
            length=1,
            position=886,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="SignoSaldoDisponible",
            length=1,
            position=887,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="Afinidad",
            length=1,
            position=888,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="Filler",
            length=47,
            position=889,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="ByteF",
            length=5,
            position=936,
            field_type=FieldType.ALPHANUMERIC
        )
    ]
    
    AFD_FIELDS: List[FieldDefinition] = [
        FieldDefinition(
            name="ByteI", 
            length=5,
            position=1,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="ModoAnalisis", 
            length=1,
            position=6,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="DiaSistema", 
            length=2,
            position=7,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="MesSistema",
            length=2,
            position=9,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="AnioSistema",
            length=4,
            position=11, 
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="HoraSistema",
            length=2,
            position=15,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="MinutoSistema",
            length=2,
            position=17,
            field_type=FieldType.NUMERIC
            ),
        FieldDefinition(
            name="CodigoKey",
            length=5,
            position=19,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="UsuarioEmisor",
            length=10,
            position=24,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="IdCliente",
            length=18,
            position=34,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodEntidad",
            length=4,
            position=52,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodTrx",
            length=6,
            position=56,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="GrupoTrx", 
            length=2,
            position=62,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="NumeroCuenta", 
            length=16,
            position=64,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="SucursalTrx", 
            length=4,
            position=80,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="RegionSucursal", 
            length=4,
            position=84,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodProd", 
            length=4,
            position=88,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodSubprod", 
            length=4,
            position=92,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="NumeroTrx", 
            length=16,
            position=96,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodRespuesta",
            length=4,
            position=112,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodRechazo",
            length=4,
            position=116,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="TipoPersona",
            length=1,
            position=120,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="IndicaReverso",
            length=1,
            position=121,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="FechaTrx",
            length=8,
            position=122,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="HoraTrx",
            length=6,
            position=130,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="ModoProceso",
            length=1,
            position=136,
            field_type=FieldType.ALPHANUMERIC
            ),
        FieldDefinition(
            name="FechaHoraTrx",
            length=14,
            position=137,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="CodMonedaTrx",
            length=3,
            position=151,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="MontoTotalTrx",
            length=17,
            position=154,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="MontoEfectivo",
            length=17,
            position=171,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="MontoChqPropio",
            length=17,
            position=188,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="MontoChqAjeno",
            length=17,
            position=205,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="NumeroCuentaOri",
            length=25,
            position=222,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="NumeroCuentaDest",
            length=25,
            position=247,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CanalMedio",
            length=4,
            position=272,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="MotivoConcepto",
            length=4,
            position=276,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="DebitoCreditoOtra",
            length=1,
            position=280,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="EstadoCtaProducto",
            length=1,
            position=281,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="NoDocumento",
            length=12,
            position=282,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="TipoChequera",
            length=1,
            position=294,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="NumIniTalonarioAh",
            length=11,
            position=295,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="NumFinTalonarioAh",
            length=11,
            position=306,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="MaxComproTalonaAh",
            length=11,
            position=317,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="NumeroIniChequera",
            length=11,
            position=328,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="NumeroFinChequera",
            length=11,
            position=339,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="MaxComproChequera",
            length=11,
            position=350,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="IndicaChequeCompe",
            length=1,
            position=361,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="FechaCompensacion",
            length=8,
            position=362,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="SignoValor",
            length=1,
            position=370,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="SaldoDisponible",
            length=17,
            position=371,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="Localidad",
            length=30,
            position=388,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="FechaAperProd",
            length=8,
            position=418,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="NumeroTerminal",
            length=10,
            position=426,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodClienteOri",
            length=12,
            position=436,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodClienteDest",
            length=12,
            position=448,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="IdClienteDest",
            length=18,
            position=460,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="SucurAperCuenta",
            length=4,
            position=478,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="SucurAperDest",
            length=4,
            position=482,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="EntidadAdquire",
            length=11,
            position=486,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="IndicaEmpleCtaOri",
            length=1,
            position=497,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="IndicaEmpleCtaDest",
            length=1,
            position=498,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodIdBancoDest",
            length=11,
            position=499,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="NumeroReferen",
            length=20,
            position=510,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="TipoPagoServ",
            length=6,
            position=530,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="FechaVinculaClien",
            length=8,
            position=536,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="CodUsuario",
            length=12,
            position=544,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodEmpleado",
            length=12,
            position=556,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodUsuarioAutori",
            length=12,
            position=568,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CodUsuarioCofirma",
            length=12,
            position=580,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="MontoSobgiroAutorizado",
            length=17,
            position=592,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="IndicaSobregiro",
            length=2,
            position=609,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="TipoCliente",
            length=2,
            position=611,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="IndicaCuentaRegis",
            length=2,
            position=613,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="KeyTransfeInterbanca",
            length=20,
            position=615,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="IdRastreoTransfe",
            length=12,
            position=635,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="DirecIP",
            length=15,
            position=647,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="DirecIPInscrita",
            length=15,
            position=662,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="NombClienTitularCtaOri",
            length=40,
            position=677,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="NombClienTitularCtaDest",
            length=40,
            position=717,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="DirecDomicilio",
            length=40,
            position=757,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="TelefonoResidencia",
            length=18,
            position=797,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="TelefonoOficina",
            length=18,
            position=815,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="TelefonoOtro",
            length=18,
            position=833,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CorreoEmail",
            length=40,
            position=851,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="Filler1",
            length=30,
            position=891,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="TipoPro",
            length=8,
            position=921,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="RedOrig",
            length=8,
            position=929,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="IndicaFraude",
            length=1,
            position=937,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="OrigenAlerta",
            length=6,
            position=938,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="IdTrxFraude",
            length=15,
            position=944,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="CountMesTransCtaOriDest",
            length=9,
            position=959,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="CountDiarioLlave4Ant",
            length=9,
            position=968,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="CountMensualLlave11Ant",
            length=9,
            position=977,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="CampoValor",
            length=1,
            position=986,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="Coincidencias",
            length=9,
            position=987,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="LocalInternacional",
            length=1,
            position=996,
            field_type=FieldType.ALPHANUMERIC
        ),
        FieldDefinition(
            name="RangoMonto",
            length=2,
            position=997,
            field_type=FieldType.NUMERIC
        ),
        FieldDefinition(
            name="ByteF",
            length=5,
            position=999,
            field_type=FieldType.ALPHANUMERIC
        )
    ]
    
    @classmethod
    def get_field_definition(cls, field_name: str, message_type: MessageType = MessageType.ACF) -> Optional[FieldDefinition]:
        """
        Obtiene la definición de un campo por su nombre.
        
        Args:
            field_name: Nombre del campo a buscar
            message_type: Tipo de mensaje (ACF o AFD)
            
        Returns:
            FieldDefinition si existe, None si no se encuentra
        """
        fields = cls.ACF_FIELDS if message_type == MessageType.ACF else cls.AFD_FIELDS
        
        for field in fields:
            if field.name == field_name:
                return field
        return None
    
    @classmethod
    def extract_field(cls, message: str, field_name: str, message_type: MessageType = MessageType.ACF) -> Optional[str]:
        """
        Extrae el valor de un campo del mensaje.
        
        Args:
            message: Mensaje completo (940 caracteres)
            field_name: Nombre del campo a extraer
            message_type: Tipo de mensaje (ACF o AFD)
            
        Returns:
            Valor extraído del campo o None si no se encuentra
        """
        field_def = cls.get_field_definition(field_name, message_type)
        
        if not field_def:
            return None
            
        start = field_def.position - 1
        end = start + field_def.length
        
        return message[start:end].strip()
    
    @classmethod
    def validate_message_length(cls, message: str) -> Optional[MessageType]:
        """
        Valida la longitud del mensaje y su tipo.
        
        Args:
            message: Mensaje a validar
            
        Returns:
            MessageType: El tipo de mensaje detectado o None si no es válido
        """
        message_lenght = len(message)
        
        if message_lenght == cls.MESSAGE_LENGHTS[MessageType.ACF]:
            return MessageType.ACF
        elif message_lenght == cls.MESSAGE_LENGHTS[MessageType.AFD]:
            return MessageType.AFD

        return None
    
    @classmethod
    def get_fields_for_message_type(cls, message_type: MessageType) -> List[FieldDefinition]:
        """
        Obtiene los campos correspondientes al tipo de mensaje.

        Args:
            message_type (MessageType): Tipo de mensaje

        Returns:
            List[FieldDefinition]: Lista de definiciones de campos
        """
        return cls.ACF_FIELDS if message_type == MessageType.ACF else cls.AFD_FIELDS
